# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyAlbum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyAlbum
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Kingfisher', '~> 5.0'

  target 'MyAlbumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAlbumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
